name: henrique-borges.dev
description: My personal blog about software engineering
meta_description: "Blog about software engineering"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "http://henrique-borges.dev"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Henrique Borges"

# Disqus config
disqus-shortname: ""
